### ISSUE TITLE
It's a great job...... and If I want to train my own data(three categories), what parameters should I change? Thanks

### ISSUE THREAD

**Issue by yangzhegithub** [jinfagang/CenterNet_Pro_Max#2]

**Comment by lucasjinreal** [comment]
thanks for your interested on this work! We will opensource some self-defined dataset training within this week, pls keep informed and stay tune!

**Comment by yangzhegithub** [comment]
@jinfagang okay, thanks. Looking forward to your opensource- -

**Comment by YaoQ** [comment]
Thanks for your great job, and I try to train the centerNet with my own dataset. It only has one object. But when I generate the dataset as  **coco_2017_train**, then train it using **ct_coco_r50_config.py** .
```
INFO 03.24 09:53:14 train_coco_r50.py:79: output will be saved into: ./checkpoints/
Traceback (most recent call last):
  File "/home/yao/train/pytorch/CenterNet_Pro_Max/models/data/catalog.py", line 76, in get
    f = DatasetCatalog._REGISTERED[name]
KeyError: 'coco_2017_train'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_coco_r50.py", line 114, in <module>
    train(args)
  File "train_coco_r50.py", line 80, in train
    trainer = Trainer(cfg, model)
  File "/home/yao/train/pytorch/CenterNet_Pro_Max/models/train/trainer.py", line 92, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/yao/train/pytorch/CenterNet_Pro_Max/models/train/trainer.py", line 222, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/home/yao/train/pytorch/CenterNet_Pro_Max/models/data/build.py", line 396, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/home/yao/train/pytorch/CenterNet_Pro_Max/models/data/build.py", line 280, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/yao/train/pytorch/CenterNet_Pro_Max/models/data/build.py", line 280, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/yao/train/pytorch/CenterNet_Pro_Max/models/data/catalog.py", line 80, in get
    name, ", ".join(DatasetCatalog._REGISTERED.keys())
KeyError: "Dataset 'coco_2017_train' is not registered! Available datasets are: "
```
Seemly I have to register the coco_2017_train  data format manully. So is there any idea I can fix that issue?
Thank you very much.

**Comment by lucasjinreal** [comment]
Master branch now support custom dataset training, coco-like format dataset training would be much more simple.

In your case, you need to check out if you manually register your dataset, simple replace coco annotation file would not work since they're differ on classes:

```
categories = ['human.pedestrian.adult',
              'human.pedestrian.child',
              'human.pedestrian.wheelchair',
              'human.pedestrian.stroller',
              'human.pedestrian.personal_mobility',
              'human.pedestrian.police_officer',
              'human.pedestrian.construction_worker',
              'vehicle.car',
              'vehicle.bus.bendy',
              'vehicle.bus.rigid',
              'vehicle.truck',
              'vehicle.construction',
              'vehicle.emergency.ambulance',
              'vehicle.emergency.police',
              'vehicle.trailer']


path = "datasets/nuScenes"
get_dicts = lambda p=path, c=categories: get_nuscenes_dicts(path=p, version='v1.0-trainval', categories=c)
DatasetCatalog.register("nusc_v1.0_trainval01", get_dicts)
MetadataCatalog.get("nusc_v1.0_trainval01").thing_classes = categories
```
This is training example on nuScenes, will update some coco-format like dataset training exmaples.

**Comment by lucasjinreal** [comment]
Custom dataset training updated.

**Comment by YaoQ** [comment]
@jinfagang  Thank you very much for reply, and I have managed to train with my own datasets according to the sample code of `train_tl_r50.py`.
Great job!
